# Computational Social Science Project #2 

**Enter your Name:**Nereida Heller

*Semester:* Fall 2024

Below we fill in some of the code you might use to answer some of the questions. Here are some additional resources for when you get stuck:
* Code and documentation provided in the course notebooks  
* [Markdown cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) to help with formatting the Jupyter notebook
* Try Googling any errors you get and consult Stack Overflow, etc. Someone has probably had your question before!
* Send me a pull request on GitHub flagging the syntax that's tripping you up

**INSTRUCTIONS:** For this project, copy all of the files in the Project 2 folder in the course repo into a "Project 2" subfolder within the "Computational Social Science Projects" directory that you created for the first project. You will work on the project locally, push your project to GitHub, and submit a link to the GitHub repo on bCourses by the project deadline. Be sure the final submission is in the main branch, which is what I'll pull down and re-run to grade.

## 1. Introduction/Setup

#### a) Import relevant libraries
Here are some libraries you will need to get started. Along the way you may need to add more. Best practice is to add them here at the top of the script.

In [47]:
#
# import libraries you might need here 
#-----------
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns


# use random seed for consistent results 
np.random.seed(273)

#### b) Read in and inspect data frame 
Read in the data frame and look at some of its attributes. Read in the data contained in the projoect folder: "Diabetes with Population Info by County 2017.csv".

In [48]:
pwd

'C:\\git\\Computational-Social-Science-Projects\\Project 2'

In [49]:
#
# read in and inspect data frame
#-----------
# Note that "CountyFips" needs to be a string so the leading 0 isn't dropped (only if you want to make choropleth map) 
diabetes = pd.read_csv("data prep/Diabetes with Population Info by County 2017.csv", 
                       dtype={"CountyFIPS": str}) 
diabetes.head()

,County,State,CountyFIPS,Diabetes_Number,Obesity_Number,Physical_Inactivity_Number,sex and age_total population_65 years and over_sex ratio (males per 100 females),race_total population,race_total population_one race,race_total population_two or more races,race_total population_one race_1,race_total population_one race_white,race_total population_one race_black or african american,race_total population_one race_american indian and alaska native,race_total population_one race_american indian and alaska native_cherokee tribal grouping,race_total population_one race_american indian and alaska native_chippewa tribal grouping,race_total population_one race_american indian and alaska native_navajo tribal grouping,race_total population_one race_american indian and alaska native_sioux tribal grouping,race_total population_one race_asian,race_total population_one race_asian_asian indian,race_total population_one race_asian_chinese,race_total population_one race_asian_filipino,race_total population_one race_asian_japanese,race_total population_one race_asian_korean,race_total population_one race_asian_vietnamese,race_total population_one race_asian_other asian,race_total population_one race_native hawaiian and other pacific islander,race_total population_one race_native hawaiian and other pacific islander_native hawaiian,race_total population_one race_native hawaiian and other pacific islander_guamanian or chamorro,race_total population_one race_native hawaiian and other pacific islander_samoan,race_total population_one race_native hawaiian and other pacific islander_other pacific islander,race_total population_one race_some other race,race_total population_two or more races_1,race_total population_two or more races_white and black or african american,race_total population_two or more races_white and american indian and alaska native,race_total population_two or more races_white and asian,race_total population_two or more races_black or african american and american indian and alaska native,race alone or in combination with one or more other races_total population,race alone or in combination with one or more other races_total population_white,race alone or in combination with one or more other races_total population_black or african american,race alone or in combination with one or more other races_total population_american indian and alaska native,race alone or in combination with one or more other races_total population_asian,race alone or in combination with one or more other races_total population_native hawaiian and other pacific islander,race alone or in combination with one or more other races_total population_some other race,hispanic or latino and race_total population,hispanic or latino and race_total population_hispanic or latino (of any race),hispanic or latino and race_total population_hispanic or latino (of any race)_mexican,hispanic or latino and race_total population_hispanic or latino (of any race)_puerto rican,hispanic or latino and race_total population_hispanic or latino (of any race)_cuban,hispanic or latino and race_total population_hispanic or latino (of any race)_other hispanic or latino,hispanic or latino and race_total population_not hispanic or latino,hispanic or latino and race_total population_not hispanic or latino_white alone,hispanic or latino and race_total population_not hispanic or latino_black or african american alone,hispanic or latino and race_total population_not hispanic or latino_american indian and alaska native alone,hispanic or latino and race_total population_not hispanic or latino_asian alone,hispanic or latino and race_total population_not hispanic or latino_native hawaiian and other pacific islander alone,hispanic or latino and race_total population_not hispanic or latino_some other race alone,hispanic or latino and race_total population_not hispanic or latino_two or more races,hispanic or latino and race_total population_not hispanic or latino_two or more races_two races including some other race,hispanic or latino and race_total population_not hispanic or latino_two or more races_two races excluding some other race - and three or more races,total housing units,citizen - voting age population_citizen - 18 and over population,citizen - voting age population_citizen - 18 and over population_male,citizen - voting age population_citizen - 18 and over population_female,sex and age_total population,sex and age_total population_male,sex and age_total population_female,sex and age_total population_sex ratio (males per 100 females),sex and age_total population_under 5 years,sex and age_total population_5 to 9 years,sex and age_total population_10 to 14 years,sex and age_total population_15 to 19 years,sex and age_total population_20 to 24 years,sex and age_total population_25 to 34 years,sex and age_total population_35 to 44 years,sex and age_total population_45 to 54 years,sex and age_total population_55 to 59 years,sex and age_total population_60 to 64 years,sex and age_total population_65 to 74 years,sex and age_total population_75 to 84 years,sex and age_total population_85 years and over,sex and age_total population_median age (years),sex and age_total population_under 18 years,sex and age_total population_16 years and over,sex and age_total population_18 years and over,sex and age_total population_21 years and over,sex and age_total population_62 years and over,sex and age_total population_65 years and over,sex and age_total population_18 years and over_1,sex and age_total population_18 years and over_male,sex and age_total population_18 years and over_female,sex and age_total population_18 years and over_sex ratio (males per 100 females),sex and age_total population_65 years and over_1,sex and age_total population_65 years and over_male,sex and age_total population_65 years and over_female
0,Autauga County,Alabama,01001,5178,13489,12525,76.5,55200,54170,1030,54170,42437,10565,159,82,0,44,0,568,0,107,120,27,88,214,12,32,0,32,0,0,409,1030,340,275,257,12,55200,43367,10962,464,895,115,427,55200,1528,737,287,207,297,53672,41412,10475,159,568,5,41,1012,0,1012,23315,41304,19747,21557,55200,26874,28326,94.9,3263,4009,3570,3855,3337,7064,7374,7853,4131,2694,4711,2524,815,37.8,13369,43368,41831,39614,9403,8050,41831,20054,21777,92.1,8050,3488,4562
1,Baldwin County,Alabama,01003,16707,48542,40024,86.6,208107,204535,3572,204535,179526,19764,1522,285,0,70,15,1680,43,661,204,478,137,128,29,9,0,9,0,0,2034,3572,408,1548,855,62,208107,182689,20311,3185,2824,79,2648,208107,9353,5129,1451,273,2500,198754,172768,19529,1398,1668,9,410,2972,352,2620,111945,159193,76318,82875,208107,101188,106919,94.6,11609,11689,14323,12707,10790,23326,25377,28330,14440,14851,24551,12165,3949,42.8,45677,167712,162430,155502,49811,40665,162430,78104,84326,92.6,40665,18870,21795
2,Barbour County,Alabama,01005,3400,8009,5431,76.2,25782,25429,353,25429,12216,12266,72,26,0,9,0,96,11,0,5,0,48,13,19,1,1,0,0,0,778,353,43,73,54,81,25782,12461,12492,301,155,1,800,25782,1106,905,89,3,109,24676,11898,12199,63,85,1,86,344,13,331,11937,19991,10648,9343,25782,13697,12085,113.3,1390,1450,1677,1434,1658,3675,3104,3452,1657,1651,2820,1392,422,39.9,5436,20948,20346,19394,5658,4634,20346,10923,9423,115.9,4634,2004,2630
3,Bibb County,Alabama,01007,2371,6534,5827,80.5,22527,22340,187,22340,17268,5018,8,0,0,0,0,37,37,0,0,0,0,0,0,0,0,0,0,0,9,187,91,82,6,0,22527,17447,5117,90,51,0,9,22527,547,200,17,28,302,21980,16801,4974,8,37,0,0,160,0,160,9161,17672,9487,8185,22527,12152,10375,117.1,1275,1178,1289,1514,1491,3075,2895,3439,1494,1216,2122,1112,427,39.9,4659,18470,17868,16864,4323,3661,17868,9578,8290,115.5,3661,1633,2028
4,Blount County,Alabama,01009,6282,14227,14365,79.7,57645,56710,935,56710,55054,862,141,20,0,0,0,198,42,47,53,9,34,0,13,18,0,18,0,0,437,935,236,531,45,0,57645,55981,1124,714,292,53,479,57645,5261,4755,107,19,380,52384,50232,820,124,198,18,174,818,0,818,24222,42627,20703,21924,57645,28434,29211,97.3,3485,3632,3995,3717,3189,6786,7153,7947,3895,3613,6132,3235,866,40.8,13468,45915,44177,42232,12400,10233,44177,21595,22582,95.6,10233,4540,5693

In [50]:
diabetes.tail()

,County,State,CountyFIPS,Diabetes_Number,Obesity_Number,Physical_Inactivity_Number,sex and age_total population_65 years and over_sex ratio (males per 100 females),race_total population,race_total population_one race,race_total population_two or more races,race_total population_one race_1,race_total population_one race_white,race_total population_one race_black or african american,race_total population_one race_american indian and alaska native,race_total population_one race_american indian and alaska native_cherokee tribal grouping,race_total population_one race_american indian and alaska native_chippewa tribal grouping,race_total population_one race_american indian and alaska native_navajo tribal grouping,race_total population_one race_american indian and alaska native_sioux tribal grouping,race_total population_one race_asian,race_total population_one race_asian_asian indian,race_total population_one race_asian_chinese,race_total population_one race_asian_filipino,race_total population_one race_asian_japanese,race_total population_one race_asian_korean,race_total population_one race_asian_vietnamese,race_total population_one race_asian_other asian,race_total population_one race_native hawaiian and other pacific islander,race_total population_one race_native hawaiian and other pacific islander_native hawaiian,race_total population_one race_native hawaiian and other pacific islander_guamanian or chamorro,race_total population_one race_native hawaiian and other pacific islander_samoan,race_total population_one race_native hawaiian and other pacific islander_other pacific islander,race_total population_one race_some other race,race_total population_two or more races_1,race_total population_two or more races_white and black or african american,race_total population_two or more races_white and american indian and alaska native,race_total population_two or more races_white and asian,race_total population_two or more races_black or african american and american indian and alaska native,race alone or in combination with one or more other races_total population,race alone or in combination with one or more other races_total population_white,race alone or in combination with one or more other races_total population_black or african american,race alone or in combination with one or more other races_total population_american indian and alaska native,race alone or in combination with one or more other races_total population_asian,race alone or in combination with one or more other races_total population_native hawaiian and other pacific islander,race alone or in combination with one or more other races_total population_some other race,hispanic or latino and race_total population,hispanic or latino and race_total population_hispanic or latino (of any race),hispanic or latino and race_total population_hispanic or latino (of any race)_mexican,hispanic or latino and race_total population_hispanic or latino (of any race)_puerto rican,hispanic or latino and race_total population_hispanic or latino (of any race)_cuban,hispanic or latino and race_total population_hispanic or latino (of any race)_other hispanic or latino,hispanic or latino and race_total population_not hispanic or latino,hispanic or latino and race_total population_not hispanic or latino_white alone,hispanic or latino and race_total population_not hispanic or latino_black or african american alone,hispanic or latino and race_total population_not hispanic or latino_american indian and alaska native alone,hispanic or latino and race_total population_not hispanic or latino_asian alone,hispanic or latino and race_total population_not hispanic or latino_native hawaiian and other pacific islander alone,hispanic or latino and race_total population_not hispanic or latino_some other race alone,hispanic or latino and race_total population_not hispanic or latino_two or more races,hispanic or latino and race_total population_not hispanic or latino_two or more races_two races including some other race,hispanic or latino and race_total population_not hispanic or latino_two or more races_two races excluding some other race - and three or more races,total housing units,citizen - voting age population_citizen - 18 and over population,citizen - voting age population_citizen - 18 and over population_male,citizen - voting age population_citizen - 18 and over population_female,sex and age_total population,sex and age_total population_male,sex and age_total population_female,sex and age_total population_sex ratio (males per 100 females),sex and age_total population_under 5 years,sex and age_total population_5 to 9 years,sex and age_total population_10 to 14 years,sex and age_total population_15 to 19 years,sex and age_total population_20 to 24 years,sex and age_total population_25 to 34 years,sex and age_total population_35 to 44 years,sex and age_total population_45 to 54 years,sex and age_total population_55 to 59 years,sex and age_total population_60 to 64 years,sex and age_total population_65 to 74 years,sex and age_total population_75 to 84 years,sex and age_total population_85 years and over,sex and age_total population_median age (years),sex and age_total population_under 18 years,sex and age_total population_16 years and over,sex and age_total population_18 years and over,sex and age_total population_21 years and over,sex and age_total population_62 years and over,sex and age_total population_65 years and over,sex and age_total population_18 years and over_1,sex and age_total population_18 years and over_male,sex and age_total population_18 years and over_female,sex and age_total population_18 years and over_sex ratio (males per 100 females),sex and age_total population_65 years and over_1,sex and age_total population_65 years and over_male,sex and age_total population_65 years and over_female
3215,Sweetwater County,Wyoming,56037,2560,9362,7518,92.0,44117,43226,891,43226,41084,354,742,0,0,241,15,279,0,49,63,3,35,22,107,204,29,0,175,0,563,891,233,213,294,0,44117,41964,602,1024,636,260,595,44117,7042,5724,31,15,1272,37075,35107,336,472,279,194,11,676,0,676,19628,30770,15983,14787,44117,22882,21235,107.8,3155,3553,3203,3157,2716,6551,6022,5274,3089,2676,3061,1215,445,34.6,11809,33529,32308,30491,6159,4721,32308,16800,15508,108.3,4721,2262,2459
3216,Teton County,Wyoming,56039,439,2051,2005,94.8,23059,22875,184,22875,20832,274,77,30,0,3,0,282,6,167,10,55,0,0,44,35,0,0,0,35,1375,184,0,97,61,0,23059,21016,274,174,347,39,1397,23059,3433,3014,94,0,325,19626,18813,245,77,282,35,12,162,0,162,13680,16730,8646,8084,23059,11911,11148,106.8,1156,1360,1352,930,1097,4239,3733,3051,1485,1521,2087,764,284,39.3,4434,18983,18625,18169,3843,3135,18625,9619,9006,106.8,3135,1526,1609
3217,Uinta County,Wyoming,56041,1440,4925,3519,97.6,20609,19891,718,19891,19252,20,160,0,0,26,59,22,0,0,8,0,10,4,0,0,0,0,0,0,437,718,31,629,0,0,20609,19970,96,834,35,13,437,20609,1884,1723,20,0,141,18725,18042,20,150,22,0,0,491,0,491,8972,14025,7084,6941,20609,10505,10104,104.0,1502,1829,1747,1477,1139,2454,2698,2335,1762,1168,1605,606,287,35.5,6071,15176,14538,13939,3251,2498,14538,7280,7258,100.3,2498,1234,1264
3218,Washakie County,Wyoming,56043,637,1738,1708,89.0,8129,7791,338,7791,7293,1,52,42,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,445,338,122,164,4,0,8129,7625,128,222,9,6,488,8129,1153,1058,1,0,94,6976,6666,1,29,0,0,13,267,21,246,3868,6134,3111,3023,8129,4137,3992,103.6,434,484,561,580,408,783,984,1021,581,607,967,528,191,43.5,1942,6557,6187,5951,2041,1686,6187,3142,3045,103.2,1686,794,892
3219,Weston County,Wyoming,56045,601,2015,1383,90.6,7100,6956,144,6956,6570,36,37,0,0,0,0,310,0,7,269,17,0,0,17,3,0,0,3,0,0,144,80,64,0,0,7100,6714,116,101,310,3,0,7100,107,62,3,0,42,6993,6466,36,37,310,0,0,144,0,144,3565,5462,2854,2608,7100,3768,3332,113.1,372,577,338,323,476,789,843,855,375,812,715,427,198,42.9,1505,5702,5595,5434,1770,1340,5595,2923,2672,109.4,1340,637,703

In [51]:
#
# look at shape
#-----------
# look at the dimensions of the diabetes data frame
print('shape: ', diabetes.shape)

shape:  (3220, 95)

In [52]:
#
# set pandas parameters
#-----------
# tells pandas how many rows to display when printing so results don't get truncated
pd.set_option('display.max_rows', 100)

# look at the data types for each column in diabetes df (likely be located under each row bc column names are long)
print('data types:', diabetes.dtypes)

data types: County                                                                                                                                                   object
State                                                                                                                                                    object
CountyFIPS                                                                                                                                               object
Diabetes_Number                                                                                                                                          object
Obesity_Number                                                                                                                                           object
Physical_Inactivity_Number                                                                                                                               object
sex and age_total population_65 years and over_sex ratio (males per 100 females)                                                                         object
race_total population                                                                                                                                     int64
race_total population_one race                                                                                                                            int64
race_total population_two or more races                                                                                                                   int64
race_total population_one race_1                                                                                                                          int64
race_total population_one race_white                                                                                                                      int64
race_total population_one race_black or african american                                                                                                  int64
race_total population_one race_american indian and alaska native                                                                                          int64
race_total population_one race_american indian and alaska native_cherokee tribal grouping                                                                 int64
race_total population_one race_american indian and alaska native_chippewa tribal grouping                                                                 int64
race_total population_one race_american indian and alaska native_navajo tribal grouping                                                                   int64
race_total population_one race_american indian and alaska native_sioux tribal grouping                                                                    int64
race_total population_one race_asian                                                                                                                      int64
race_total population_one race_asian_asian indian                                                                                                         int64
race_total population_one race_asian_chinese                                                                                                              int64
race_total population_one race_asian_filipino                                                                                                             int64
race_total population_one race_asian_japanese                                                                                                             int64
race_total population_one race_asian_korean                                                                                                               int64
race_total population_one race_asian_vietnamese                                                                                                           int64
race_total population_one race_asian_other asian                                                                                                          int64
race_total population_one race_native hawaiian and other pacific islander                                                                                 int64
race_total population_one race_native hawaiian and other pacific islander_native hawaiian                                                                 int64
race_total population_one race_native hawaiian and other pacific islander_guamanian or chamorro                                                           int64
race_total population_one race_native hawaiian and other pacific islander_samoan                                                                          int64
race_total population_one race_native hawaiian and other pacific islander_other pacific islander                                                          int64
race_total population_one race_some other race                                                                                                            int64
race_total population_two or more races_1                                                                                                                 int64
race_total population_two or more races_white and black or african american                                                                               int64
race_total population_two or more races_white and american indian and alaska native                                                                       int64
race_total population_two or more races_white and asian                                                                                                   int64
race_total population_two or more races_black or african american and american indian and alaska native                                                   int64
race alone or in combination with one or more other races_total population                                                                                int64
race alone or in combination with one or more other races_total population_white                                                                          int64
race alone or in combination with one or more other races_total population_black or african american                                                      int64
race alone or in combination with one or more other races_total population_american indian and alaska native                                              int64
race alone or in combination with one or more other races_total population_asian                                                                          int64
race alone or in combination with one or more other races_total population_native hawaiian and other pacific islander                                     int64
race alone or in combination with one or more other races_total population_some other race                                                                int64
hispanic or latino and race_total population                                                                                                              int64
hispanic or latino and race_total population_hispanic or latino (of any race)                                                                             int64
hispanic or latino and race_total population_hispanic or latino (of any race)_mexican                                                                     int64
hispanic or latino and race_total population_hispanic or latino (of any race)_puerto rican                                                                int64
hispanic or latino and race_total population_hispanic or latino (of any race)_cuban                                                                       int64
hispanic or latino and race_total population_hispanic or latino (of any race)_other hispanic or latino                                                    int64
hispanic or latino and race_total population_not hispanic or latino                                                                                       int64
hispanic or latino and race_total population_not hispanic or latino_white alone                                                                           int64
hispanic or latino and race_total population_not hispanic or latino_black or african american alone                                                       int64
hispanic or latino and race_total population_not hispanic or latino_american indian and alaska native alone                                               int64
hispanic or latino and race_total population_not hispanic or latino_asian alone                                                                           int64
hispanic or latino and race_total population_not hispanic or latino_native hawaiian and other pacific islander alone                                      int64
hispanic or latino and race_total population_not hispanic or latino_some other race alone                                                                 int64
hispanic or latino and race_total population_not hispanic or latino_two or more races                                                                     int64
hispanic or latino and race_total population_not hispanic or latino_two or more races_two races including some other race                                 int64
hispanic or latino and race_total population_not hispanic or latino_two or more races_two races excluding some other race -  and three or more races      int64
total housing units                                                                                                                                       int64
citizen -  voting age population_citizen -  18 and over population                                                                                        int64
citizen -  voting age population_citizen -  18 and over population_male                                                                                   int64
citizen -  voting age population_citizen -  18 and over population_female                                                                                 int64
sex and age_total population                                                                                                                              int64
sex and age_total population_male                                                                                                                         int64
sex and age_total population_female                                                                                                                       int64
sex and age_total population_sex ratio (males per 100 females)                                                                                          float64
sex and age_total population_under 5 years                                                                                                                int64
sex and age_total population_5 to 9 years                                                                                                                 int64
sex and age_total population_10 to 14 years                                                                                                               int64
sex and age_total population_15 to 19 years                                                                                                               int64
sex and age_total population_20 to 24 years                                                                                                               int64
sex and age_total population_25 to 34 years                                                                                                               int64
sex and age_total population_35 to 44 years                                                                                                               int64
sex and age_total population_45 to 54 years                                                                                                               int64
sex and age_total population_55 to 59 years                                                                                                               int64
sex and age_total population_60 to 64 years                                                                                                               int64
sex and age_total population_65 to 74 years                                                                                                               int64
sex and age_total population_75 to 84 years                                                                                                               int64
sex and age_total population_85 years and over                                                                                                            int64
sex and age_total population_median age (years)                                                                                                         float64
sex and age_total population_under 18 years                                                                                                               int64
sex and age_total population_16 years and over                                                                                                            int64
sex and age_total population_18 years and over                                                                                                            int64
sex and age_total population_21 years and over                                                                                                            int64
sex and age_total population_62 years and over                                                                                                            int64
sex and age_total population_65 years and over                                                                                                            int64
sex and age_total population_18 years and over_1                                                                                                          int64
sex and age_total population_18 years and over_male                                                                                                       int64
sex and age_total population_18 years and over_female                                                                                                     int64
sex and age_total population_18 years and over_sex ratio (males per 100 females)                                                                        float64
sex and age_total population_65 years and over_1                                                                                                          int64
sex and age_total population_65 years and over_male                                                                                                       int64
sex and age_total population_65 years and over_female                                                                                                     int64
dtype: object

Immediately, we see that some of the features that should be numeric (e.g., Diabetes_Number, Obesity_Number,  and Physical_Inactivity_Number) are not. We can check to see what the non-numeric values are in a column where we are expecting numeric information with a combination of `str.isnumeric()` and `unique()`.

In [53]:
#
# identify non-numeric features
#-----------
# Return rows where the column "Diabetes_Number" is non-numeric and get the unique values of these rows
# the "~" below in front of diabetes negates the str.isnumeric() so it only takes non-numeric values
print(diabetes[~diabetes["Diabetes_Number"].str.isnumeric()]["Diabetes_Number"].unique())

['Suppressed']

In [54]:
#
# Now do the same as above, but for "Obesity_Number"
#-----------
print(diabetes[~diabetes["Obesity_Number"].str.isnumeric()]["Obesity_Number"].unique())

['No Data']

In [55]:
#
# Now do the same as above, but for "Physical_Inactivity_Number" 
#-----------
print(diabetes[~diabetes["Physical_Inactivity_Number"].str.isnumeric()]["Physical_Inactivity_Number"].unique())

['No Data']

These values ("Suppresssed" and "No Data") contained in the two respective columns are coercing these features to objects instead of them being  integers. Let's drop those rows in the next section, and also recode "Physical_Inactivity_Number" feature to be an integer.

#### c. Recode variables

Convert 'Diabetes_Number', 'Obesity_Number', and 'Physical_Inactivity_Number' to integers below so we can use them in our analysis. Also fill in the object type we want to recode 'sex and age_total population_65 years and over_sex ratio (males per 100 females)' too (you'll have to scroll all the way over to the right).

In [56]:
#before
print('data types:', diabetes.dtypes)

data types: County                                                                                                                                                   object
State                                                                                                                                                    object
CountyFIPS                                                                                                                                               object
Diabetes_Number                                                                                                                                          object
Obesity_Number                                                                                                                                           object
Physical_Inactivity_Number                                                                                                                               object
sex and age_total population_65 years and over_sex ratio (males per 100 females)                                                                         object
race_total population                                                                                                                                     int64
race_total population_one race                                                                                                                            int64
race_total population_two or more races                                                                                                                   int64
race_total population_one race_1                                                                                                                          int64
race_total population_one race_white                                                                                                                      int64
race_total population_one race_black or african american                                                                                                  int64
race_total population_one race_american indian and alaska native                                                                                          int64
race_total population_one race_american indian and alaska native_cherokee tribal grouping                                                                 int64
race_total population_one race_american indian and alaska native_chippewa tribal grouping                                                                 int64
race_total population_one race_american indian and alaska native_navajo tribal grouping                                                                   int64
race_total population_one race_american indian and alaska native_sioux tribal grouping                                                                    int64
race_total population_one race_asian                                                                                                                      int64
race_total population_one race_asian_asian indian                                                                                                         int64
race_total population_one race_asian_chinese                                                                                                              int64
race_total population_one race_asian_filipino                                                                                                             int64
race_total population_one race_asian_japanese                                                                                                             int64
race_total population_one race_asian_korean                                                                                                               int64
race_total population_one race_asian_vietnamese                                                                                                           int64
race_total population_one race_asian_other asian                                                                                                          int64
race_total population_one race_native hawaiian and other pacific islander                                                                                 int64
race_total population_one race_native hawaiian and other pacific islander_native hawaiian                                                                 int64
race_total population_one race_native hawaiian and other pacific islander_guamanian or chamorro                                                           int64
race_total population_one race_native hawaiian and other pacific islander_samoan                                                                          int64
race_total population_one race_native hawaiian and other pacific islander_other pacific islander                                                          int64
race_total population_one race_some other race                                                                                                            int64
race_total population_two or more races_1                                                                                                                 int64
race_total population_two or more races_white and black or african american                                                                               int64
race_total population_two or more races_white and american indian and alaska native                                                                       int64
race_total population_two or more races_white and asian                                                                                                   int64
race_total population_two or more races_black or african american and american indian and alaska native                                                   int64
race alone or in combination with one or more other races_total population                                                                                int64
race alone or in combination with one or more other races_total population_white                                                                          int64
race alone or in combination with one or more other races_total population_black or african american                                                      int64
race alone or in combination with one or more other races_total population_american indian and alaska native                                              int64
race alone or in combination with one or more other races_total population_asian                                                                          int64
race alone or in combination with one or more other races_total population_native hawaiian and other pacific islander                                     int64
race alone or in combination with one or more other races_total population_some other race                                                                int64
hispanic or latino and race_total population                                                                                                              int64
hispanic or latino and race_total population_hispanic or latino (of any race)                                                                             int64
hispanic or latino and race_total population_hispanic or latino (of any race)_mexican                                                                     int64
hispanic or latino and race_total population_hispanic or latino (of any race)_puerto rican                                                                int64
hispanic or latino and race_total population_hispanic or latino (of any race)_cuban                                                                       int64
hispanic or latino and race_total population_hispanic or latino (of any race)_other hispanic or latino                                                    int64
hispanic or latino and race_total population_not hispanic or latino                                                                                       int64
hispanic or latino and race_total population_not hispanic or latino_white alone                                                                           int64
hispanic or latino and race_total population_not hispanic or latino_black or african american alone                                                       int64
hispanic or latino and race_total population_not hispanic or latino_american indian and alaska native alone                                               int64
hispanic or latino and race_total population_not hispanic or latino_asian alone                                                                           int64
hispanic or latino and race_total population_not hispanic or latino_native hawaiian and other pacific islander alone                                      int64
hispanic or latino and race_total population_not hispanic or latino_some other race alone                                                                 int64
hispanic or latino and race_total population_not hispanic or latino_two or more races                                                                     int64
hispanic or latino and race_total population_not hispanic or latino_two or more races_two races including some other race                                 int64
hispanic or latino and race_total population_not hispanic or latino_two or more races_two races excluding some other race -  and three or more races      int64
total housing units                                                                                                                                       int64
citizen -  voting age population_citizen -  18 and over population                                                                                        int64
citizen -  voting age population_citizen -  18 and over population_male                                                                                   int64
citizen -  voting age population_citizen -  18 and over population_female                                                                                 int64
sex and age_total population                                                                                                                              int64
sex and age_total population_male                                                                                                                         int64
sex and age_total population_female                                                                                                                       int64
sex and age_total population_sex ratio (males per 100 females)                                                                                          float64
sex and age_total population_under 5 years                                                                                                                int64
sex and age_total population_5 to 9 years                                                                                                                 int64
sex and age_total population_10 to 14 years                                                                                                               int64
sex and age_total population_15 to 19 years                                                                                                               int64
sex and age_total population_20 to 24 years                                                                                                               int64
sex and age_total population_25 to 34 years                                                                                                               int64
sex and age_total population_35 to 44 years                                                                                                               int64
sex and age_total population_45 to 54 years                                                                                                               int64
sex and age_total population_55 to 59 years                                                                                                               int64
sex and age_total population_60 to 64 years                                                                                                               int64
sex and age_total population_65 to 74 years                                                                                                               int64
sex and age_total population_75 to 84 years                                                                                                               int64
sex and age_total population_85 years and over                                                                                                            int64
sex and age_total population_median age (years)                                                                                                         float64
sex and age_total population_under 18 years                                                                                                               int64
sex and age_total population_16 years and over                                                                                                            int64
sex and age_total population_18 years and over                                                                                                            int64
sex and age_total population_21 years and over                                                                                                            int64
sex and age_total population_62 years and over                                                                                                            int64
sex and age_total population_65 years and over                                                                                                            int64
sex and age_total population_18 years and over_1                                                                                                          int64
sex and age_total population_18 years and over_male                                                                                                       int64
sex and age_total population_18 years and over_female                                                                                                     int64
sex and age_total population_18 years and over_sex ratio (males per 100 females)                                                                        float64
sex and age_total population_65 years and over_1                                                                                                          int64
sex and age_total population_65 years and over_male                                                                                                       int64
sex and age_total population_65 years and over_female                                                                                                     int64
dtype: object

In [57]:
#
# Recode variables
#-----------

# Diabetes
# ----------
# keep only useful info about our target feature, i.e., where diabetes_number not = 'Suppressed'
# note that the inside reference to the diabetes df identifies the column, and the outer calls specific rows according to a condition 
diabetes = diabetes[diabetes['Diabetes_Number']!="Suppressed"] 

# use the astype method on Diabetes_Number to convert it to an integer...if you are not sure, what does the astype() documentation tell you are possible arguments? 
diabetes['Diabetes_Number'] = diabetes['Diabetes_Number'].astype(int) 

# Obesity
# ----------
#dropping "No Data" columns
diabetes = diabetes[diabetes['Obesity_Number']!="No Data"] 

#convert to int
diabetes['Obesity_Number'] = diabetes['Obesity_Number'].astype(int) 

# Physical Inactivity
# ----------
#dropping "No Data" columns
diabetes = diabetes[diabetes['Physical_Inactivity_Number']!="No Data"] 

#convert to int
diabetes['Physical_Inactivity_Number'] = diabetes['Physical_Inactivity_Number'].astype(int) 

# Some final changes 
# ----------
# 65+ sex ratio had one "-" in it so let's drop that row first
diabetes = diabetes[diabetes['sex and age_total population_65 years and over_sex ratio (males per 100 females)']!= "-"]

# change to numeric from string, since it originally included the "-", which made it a string
# you'll have to decide whether to make it integer or float 
diabetes['sex and age_total population_65 years and over_sex ratio (males per 100 females)'] = diabetes['sex and age_total population_65 years and over_sex ratio (males per 100 females)'].astype(float)

In [58]:
#after
print('data types:', diabetes.dtypes)

data types: County                                                                                                                                                   object
State                                                                                                                                                    object
CountyFIPS                                                                                                                                               object
Diabetes_Number                                                                                                                                           int32
Obesity_Number                                                                                                                                            int32
Physical_Inactivity_Number                                                                                                                                int32
sex and age_total population_65 years and over_sex ratio (males per 100 females)                                                                        float64
race_total population                                                                                                                                     int64
race_total population_one race                                                                                                                            int64
race_total population_two or more races                                                                                                                   int64
race_total population_one race_1                                                                                                                          int64
race_total population_one race_white                                                                                                                      int64
race_total population_one race_black or african american                                                                                                  int64
race_total population_one race_american indian and alaska native                                                                                          int64
race_total population_one race_american indian and alaska native_cherokee tribal grouping                                                                 int64
race_total population_one race_american indian and alaska native_chippewa tribal grouping                                                                 int64
race_total population_one race_american indian and alaska native_navajo tribal grouping                                                                   int64
race_total population_one race_american indian and alaska native_sioux tribal grouping                                                                    int64
race_total population_one race_asian                                                                                                                      int64
race_total population_one race_asian_asian indian                                                                                                         int64
race_total population_one race_asian_chinese                                                                                                              int64
race_total population_one race_asian_filipino                                                                                                             int64
race_total population_one race_asian_japanese                                                                                                             int64
race_total population_one race_asian_korean                                                                                                               int64
race_total population_one race_asian_vietnamese                                                                                                           int64
race_total population_one race_asian_other asian                                                                                                          int64
race_total population_one race_native hawaiian and other pacific islander                                                                                 int64
race_total population_one race_native hawaiian and other pacific islander_native hawaiian                                                                 int64
race_total population_one race_native hawaiian and other pacific islander_guamanian or chamorro                                                           int64
race_total population_one race_native hawaiian and other pacific islander_samoan                                                                          int64
race_total population_one race_native hawaiian and other pacific islander_other pacific islander                                                          int64
race_total population_one race_some other race                                                                                                            int64
race_total population_two or more races_1                                                                                                                 int64
race_total population_two or more races_white and black or african american                                                                               int64
race_total population_two or more races_white and american indian and alaska native                                                                       int64
race_total population_two or more races_white and asian                                                                                                   int64
race_total population_two or more races_black or african american and american indian and alaska native                                                   int64
race alone or in combination with one or more other races_total population                                                                                int64
race alone or in combination with one or more other races_total population_white                                                                          int64
race alone or in combination with one or more other races_total population_black or african american                                                      int64
race alone or in combination with one or more other races_total population_american indian and alaska native                                              int64
race alone or in combination with one or more other races_total population_asian                                                                          int64
race alone or in combination with one or more other races_total population_native hawaiian and other pacific islander                                     int64
race alone or in combination with one or more other races_total population_some other race                                                                int64
hispanic or latino and race_total population                                                                                                              int64
hispanic or latino and race_total population_hispanic or latino (of any race)                                                                             int64
hispanic or latino and race_total population_hispanic or latino (of any race)_mexican                                                                     int64
hispanic or latino and race_total population_hispanic or latino (of any race)_puerto rican                                                                int64
hispanic or latino and race_total population_hispanic or latino (of any race)_cuban                                                                       int64
hispanic or latino and race_total population_hispanic or latino (of any race)_other hispanic or latino                                                    int64
hispanic or latino and race_total population_not hispanic or latino                                                                                       int64
hispanic or latino and race_total population_not hispanic or latino_white alone                                                                           int64
hispanic or latino and race_total population_not hispanic or latino_black or african american alone                                                       int64
hispanic or latino and race_total population_not hispanic or latino_american indian and alaska native alone                                               int64
hispanic or latino and race_total population_not hispanic or latino_asian alone                                                                           int64
hispanic or latino and race_total population_not hispanic or latino_native hawaiian and other pacific islander alone                                      int64
hispanic or latino and race_total population_not hispanic or latino_some other race alone                                                                 int64
hispanic or latino and race_total population_not hispanic or latino_two or more races                                                                     int64
hispanic or latino and race_total population_not hispanic or latino_two or more races_two races including some other race                                 int64
hispanic or latino and race_total population_not hispanic or latino_two or more races_two races excluding some other race -  and three or more races      int64
total housing units                                                                                                                                       int64
citizen -  voting age population_citizen -  18 and over population                                                                                        int64
citizen -  voting age population_citizen -  18 and over population_male                                                                                   int64
citizen -  voting age population_citizen -  18 and over population_female                                                                                 int64
sex and age_total population                                                                                                                              int64
sex and age_total population_male                                                                                                                         int64
sex and age_total population_female                                                                                                                       int64
sex and age_total population_sex ratio (males per 100 females)                                                                                          float64
sex and age_total population_under 5 years                                                                                                                int64
sex and age_total population_5 to 9 years                                                                                                                 int64
sex and age_total population_10 to 14 years                                                                                                               int64
sex and age_total population_15 to 19 years                                                                                                               int64
sex and age_total population_20 to 24 years                                                                                                               int64
sex and age_total population_25 to 34 years                                                                                                               int64
sex and age_total population_35 to 44 years                                                                                                               int64
sex and age_total population_45 to 54 years                                                                                                               int64
sex and age_total population_55 to 59 years                                                                                                               int64
sex and age_total population_60 to 64 years                                                                                                               int64
sex and age_total population_65 to 74 years                                                                                                               int64
sex and age_total population_75 to 84 years                                                                                                               int64
sex and age_total population_85 years and over                                                                                                            int64
sex and age_total population_median age (years)                                                                                                         float64
sex and age_total population_under 18 years                                                                                                               int64
sex and age_total population_16 years and over                                                                                                            int64
sex and age_total population_18 years and over                                                                                                            int64
sex and age_total population_21 years and over                                                                                                            int64
sex and age_total population_62 years and over                                                                                                            int64
sex and age_total population_65 years and over                                                                                                            int64
sex and age_total population_18 years and over_1                                                                                                          int64
sex and age_total population_18 years and over_male                                                                                                       int64
sex and age_total population_18 years and over_female                                                                                                     int64
sex and age_total population_18 years and over_sex ratio (males per 100 females)                                                                        float64
sex and age_total population_65 years and over_1                                                                                                          int64
sex and age_total population_65 years and over_male                                                                                                       int64
sex and age_total population_65 years and over_female                                                                                                     int64
dtype: object

We should probably scale our count variables to be proportional to county population. We create the list 'rc_cols' to select all the features we want to rescale, and then use the `.div()` method to avoid typing out every single column we want to recode.

In [59]:
#
# Scale to county populations (express as percentage of county total population)
#-----------

# select count variables to recode to percentages; make sure we leave out ratios and our population variable 
# because these don't make sense to scale by population
rc_cols = [col for col in diabetes.columns if col not in ['County', 'State', 'CountyFIPS', 
                                                        'sex and age_total population_65 years and over_sex ratio (males per 100 females)', 
                                                        'sex and age_total population_sex ratio (males per 100 females)', 
                                                        'sex and age_total population_18 years and over_sex ratio (males per 100 females)',  
                                                        'race_total population']]
           
# recode all selected columns to numeric
diabetes[rc_cols] = diabetes[rc_cols].apply(pd.to_numeric, errors='coerce') 

# divide all columns but those listed above by total population to calculate rates
diabetes[rc_cols] = diabetes[rc_cols].div(diabetes['race_total population'], axis=0)

Let's check our work. Are all rates bounded by 0 and 1 as expected?

In [60]:
diabetes.head()

,County,State,CountyFIPS,Diabetes_Number,Obesity_Number,Physical_Inactivity_Number,sex and age_total population_65 years and over_sex ratio (males per 100 females),race_total population,race_total population_one race,race_total population_two or more races,race_total population_one race_1,race_total population_one race_white,race_total population_one race_black or african american,race_total population_one race_american indian and alaska native,race_total population_one race_american indian and alaska native_cherokee tribal grouping,race_total population_one race_american indian and alaska native_chippewa tribal grouping,race_total population_one race_american indian and alaska native_navajo tribal grouping,race_total population_one race_american indian and alaska native_sioux tribal grouping,race_total population_one race_asian,race_total population_one race_asian_asian indian,race_total population_one race_asian_chinese,race_total population_one race_asian_filipino,race_total population_one race_asian_japanese,race_total population_one race_asian_korean,race_total population_one race_asian_vietnamese,race_total population_one race_asian_other asian,race_total population_one race_native hawaiian and other pacific islander,race_total population_one race_native hawaiian and other pacific islander_native hawaiian,race_total population_one race_native hawaiian and other pacific islander_guamanian or chamorro,race_total population_one race_native hawaiian and other pacific islander_samoan,race_total population_one race_native hawaiian and other pacific islander_other pacific islander,race_total population_one race_some other race,race_total population_two or more races_1,race_total population_two or more races_white and black or african american,race_total population_two or more races_white and american indian and alaska native,race_total population_two or more races_white and asian,race_total population_two or more races_black or african american and american indian and alaska native,race alone or in combination with one or more other races_total population,race alone or in combination with one or more other races_total population_white,race alone or in combination with one or more other races_total population_black or african american,race alone or in combination with one or more other races_total population_american indian and alaska native,race alone or in combination with one or more other races_total population_asian,race alone or in combination with one or more other races_total population_native hawaiian and other pacific islander,race alone or in combination with one or more other races_total population_some other race,hispanic or latino and race_total population,hispanic or latino and race_total population_hispanic or latino (of any race),hispanic or latino and race_total population_hispanic or latino (of any race)_mexican,hispanic or latino and race_total population_hispanic or latino (of any race)_puerto rican,hispanic or latino and race_total population_hispanic or latino (of any race)_cuban,hispanic or latino and race_total population_hispanic or latino (of any race)_other hispanic or latino,hispanic or latino and race_total population_not hispanic or latino,hispanic or latino and race_total population_not hispanic or latino_white alone,hispanic or latino and race_total population_not hispanic or latino_black or african american alone,hispanic or latino and race_total population_not hispanic or latino_american indian and alaska native alone,hispanic or latino and race_total population_not hispanic or latino_asian alone,hispanic or latino and race_total population_not hispanic or latino_native hawaiian and other pacific islander alone,hispanic or latino and race_total population_not hispanic or latino_some other race alone,hispanic or latino and race_total population_not hispanic or latino_two or more races,hispanic or latino and race_total population_not hispanic or latino_two or more races_two races including some other race,hispanic or latino and race_total population_not hispanic or latino_two or more races_two races excluding some other race - and three or more races,total housing units,citizen - voting age population_citizen - 18 and over population,citizen - voting age population_citizen - 18 and over population_male,citizen - voting age population_citizen - 18 and over population_female,sex and age_total population,sex and age_total population_male,sex and age_total population_female,sex and age_total population_sex ratio (males per 100 females),sex and age_total population_under 5 years,sex and age_total population_5 to 9 years,sex and age_total population_10 to 14 years,sex and age_total population_15 to 19 years,sex and age_total population_20 to 24 years,sex and age_total population_25 to 34 years,sex and age_total population_35 to 44 years,sex and age_total population_45 to 54 years,sex and age_total population_55 to 59 years,sex and age_total population_60 to 64 years,sex and age_total population_65 to 74 years,sex and age_total population_75 to 84 years,sex and age_total population_85 years and over,sex and age_total population_median age (years),sex and age_total population_under 18 years,sex and age_total population_16 years and over,sex and age_total population_18 years and over,sex and age_total population_21 years and over,sex and age_total population_62 years and over,sex and age_total population_65 years and over,sex and age_total population_18 years and over_1,sex and age_total population_18 years and over_male,sex and age_total population_18 years and over_female,sex and age_total population_18 years and over_sex ratio (males per 100 females),sex and age_total population_65 years and over_1,sex and age_total population_65 years and over_male,sex and age_total population_65 years and over_female
0,Autauga County,Alabama,01001,0.093804,0.244366,0.226902,76.5,55200,0.981341,0.018659,0.981341,0.768786,0.191395,0.002880,0.001486,0.0,0.000797,0.000000,0.010290,0.000000,0.001938,0.002174,0.000489,0.001594,0.003877,0.000217,0.000580,0.000000,0.000580,0.0,0.0,0.007409,0.018659,0.006159,0.004982,0.004656,0.000217,1.0,0.785634,0.198587,0.008406,0.016214,0.002083,0.007736,1.0,0.027681,0.013351,0.005199,0.003750,0.005380,0.972319,0.750217,0.189764,0.002880,0.010290,0.000091,0.000743,0.018333,0.000000,0.018333,0.422373,0.748261,0.357736,0.390525,1.0,0.486848,0.513152,94.9,0.059112,0.072627,0.064674,0.069837,0.060453,0.127971,0.133587,0.142264,0.074837,0.048804,0.085344,0.045725,0.014764,0.000685,0.242192,0.785652,0.757808,0.717645,0.170344,0.145833,0.757808,0.363297,0.394511,92.1,0.145833,0.063188,0.082645
1,Baldwin County,Alabama,01003,0.080281,0.233255,0.192324,86.6,208107,0.982836,0.017164,0.982836,0.862662,0.094970,0.007314,0.001369,0.0,0.000336,0.000072,0.008073,0.000207,0.003176,0.000980,0.002297,0.000658,0.000615,0.000139,0.000043,0.000000,0.000043,0.0,0.0,0.009774,0.017164,0.001961,0.007438,0.004108,0.000298,1.0,0.877861,0.097599,0.015305,0.013570,0.000380,0.012724,1.0,0.044943,0.024646,0.006972,0.001312,0.012013,0.955057,0.830188,0.093841,0.006718,0.008015,0.000043,0.001970,0.014281,0.001691,0.012590,0.537920,0.764957,0.366725,0.398233,1.0,0.486231,0.513769,94.6,0.055784,0.056168,0.068825,0.061060,0.051848,0.112087,0.121942,0.136132,0.069387,0.071362,0.117973,0.058456,0.018976,0.000206,0.219488,0.805893,0.780512,0.747221,0.239353,0.195404,0.780512,0.375307,0.405205,92.6,0.195404,0.090675,0.104730
2,Barbour County,Alabama,01005,0.131875,0.310643,0.210651,76.2,25782,0.986308,0.013692,0.986308,0.473819,0.475758,0.002793,0.001008,0.0,0.000349,0.000000,0.003724,0.000427,0.000000,0.000194,0.000000,0.001862,0.000504,0.000737,0.000039,0.000039,0.000000,0.0,0.0,0.030176,0.013692,0.001668,0.002831,0.002094,0.003142,1.0,0.483322,0.484524,0.011675,0.006012,0.000039,0.031029,1.0,0.042898,0.035102,0.003452,0.000116,0.004228,0.957102,0.461485,0.473160,0.002444,0.003297,0.000039,0.003336,0.013343,0.000504,0.012838,0.462997,0.775386,0.413001,0.362385,1.0,0.531262,0.468738,113.3,0.053914,0.056241,0.065045,0.055620,0.064308,0.142541,0.120394,0.133892,0.064270,0.064037,0.109379,0.053991,0.016368,0.001548,0.210845,0.812505,0.789155,0.752230,0.219455,0.179738,0.789155,0.423668,0.365488,115.9,0.179738,0.077729,0.102009
3,Bibb County,Alabama,01007,0.105251,0.290052,0.258667,80.5,22527,0.991699,0.008301,0.991699,0.766547,0.222755,0.000355,0.000000,0.0,0.000000,0.000000,0.001642,0.001642,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000400,0.008301,0.004040,0.003640,0.000266,0.000000,1.0,0.774493,0.227150,0.003995,0.002264,0.000000,0.000400,1.0,0.024282,0.008878,0.000755,0.001243,0.013406,0.975718,0.745816,0.220802,0.000355,0.001642,0.000000,0.000000,0.007103,0.000000,0.007103,0.406668,0.784481,0.421139,0.363342,1.0,0.539442,0.460558,117.1,0.056599,0.052293,0.057220,0.067208,0.066187,0.136503,0.128512,0.152661,0.066320,0.053980,0.094198,0.049363,0.018955,0.001771,0.206818,0.819905,0.793182,0.748613,0.191903,0.162516,0.793182,0.425179,0.368003,115.5,0.162516,0.072491,0.090025
4,Blount County,Alabama,01009,0.108977,0.246804,0.249198,79.7,57645,0.983780,0.016220,0.983780,0.955052,0.014954,0.002446,0.000347,0.0,0.000000,0.000000,0.003435,0.000729,0.000815,0.000919,0.000156,0.000590,0.000000,0.000226,0.000312,0.000000,0.000312,0.0,0.0,0.007581,0.016220,0.004094,0.009212,0.000781,0.000000,1.0,0.971134,0.019499,0.012386,0.005065,0.000919,0.008309,1.0,0.091266,0.082488,0.001856,0.000330,0.006592,0.908734,0.871403,0.014225,0.002151,0.003435,0.000312,0.003018,0.014190,0.000000,0.014190,0.420193,0.739474,0.359147,0.380328,1.0,0.493260,0.506740,97.3,0.060456,0.063006,0.069303,0.064481,0.055321,0.117721,0.124087,0.137861,0.067569,0.062677,0.106375,0.056119,0.015023,0.000708,0.233637,0.796513,0.766363,0.732622,0.215110,0.177518,0.766363,0.374621,0.391743,95.6,0.177518,0.078758,0.098760

In [61]:
#
# check
#-----------
# set pandas options
pd.set_option('display.max_columns', None)

# inspect recoded values
diabetes_summary = diabetes.describe().transpose() # note we use the transpose method rather than .T because this object is not a numpy array

#(exporting for understanding)
diabetes.to_csv("diabetes_data_mod.csv", index=False)
  
# check recoding 
with pd.option_context('display.max_rows', 100, 'display.max_columns', None): 
    display(diabetes_summary.iloc[ : ,[0,1,3,7]]) # select which columns in the summary table we want to present

,count,mean,min,max
Diabetes_Number,3112.0,0.092857,0.019038,2.242079e-01
Obesity_Number,3112.0,0.251666,0.088946,4.767883e-01
Physical_Inactivity_Number,3112.0,0.200861,0.064949,3.922853e-01
sex and age_total population_65 years and over_sex ratio (males per 100 females),3112.0,84.275643,34.700000,2.200000e+02
race_total population,3112.0,103682.624036,228.000000,1.009805e+07
race_total population_one race,3112.0,0.976059,0.713126,1.000000e+00
race_total population_two or more races,3112.0,0.023941,0.000000,2.868743e-01
race_total population_one race_1,3112.0,0.976059,0.713126,1.000000e+00
race_total population_one race_white,3112.0,0.831107,0.038912,1.000000e+00
race_total population_one race_black or african american,3112.0,0.090215,0.000000,8.741228e-01
race_total population_one race_american indian and alaska native,3112.0,0.019398,0.000000,9.247994e-01
race_total population_one race_american indian and alaska native_cherokee tribal grouping,3112.0,0.001791,0.000000,4.096685e-01
race_total population_one race_american indian and alaska native_chippewa tribal grouping,3112.0,0.001338,0.000000,7.264946e-01
race_total population_one race_american indian and alaska native_navajo tribal grouping,3112.0,0.001229,0.000000,7.054752e-01
race_total population_one race_american indian and alaska native_sioux tribal grouping,3112.0,0.003315,0.000000,8.339016e-01
race_total population_one race_asian,3112.0,0.013749,0.000000,4.251072e-01
race_total population_one race_asian_asian indian,3112.0,0.002628,0.000000,1.544929e-01
race_total population_one race_asian_chinese,3112.0,0.002644,0.000000,2.128881e-01
race_total population_one race_asian_filipino,3112.0,0.002744,0.000000,3.490435e-01
race_total population_one race_asian_japanese,3112.0,0.000707,0.000000,1.396858e-01
race_total population_one race_asian_korean,3112.0,0.001174,0.000000,6.200544e-02
race_total population_one race_asian_vietnamese,3112.0,0.001255,0.000000,6.901935e-02
race_total population_one race_asian_other asian,3112.0,0.002598,0.000000,1.074529e-01
race_total population_one race_native hawaiian and other pacific islander,3112.0,0.000874,0.000000,1.244574e-01
race_total population_one race_native hawaiian and other pacific islander_native hawaiian,3112.0,0.000303,0.000000,9.545781e-02
race_total population_one race_native hawaiian and other pacific islander_guamanian or chamorro,3112.0,0.000142,0.000000,1.071603e-02
race_total population_one race_native hawaiian and other pacific islander_samoan,3112.0,0.000134,0.000000,1.895652e-02
race_total population_one race_native hawaiian and other pacific islander_other pacific islander,3112.0,0.000295,0.000000,2.813683e-02
race_total population_one race_some other race,3112.0,0.020716,0.000000,5.700959e-01
race_total population_two or more races_1,3112.0,0.023941,0.000000,2.868743e-01
race_total population_two or more races_white and black or african american,3112.0,0.006444,0.000000,6.872038e-02
race_total population_two or more races_white and american indian and alaska native,3112.0,0.008618,0.000000,1.496241e-01
race_total population_two or more races_white and asian,3112.0,0.003021,0.000000,5.465950e-02
race_total population_two or more races_black or african american and american indian and alaska native,3112.0,0.000652,0.000000,1.833862e-02
race alone or in combination with one or more other races_total population,3112.0,1.000000,1.000000,1.000000e+00
race alone or in combination with one or more other races_total population_white,3112.0,0.852907,0.069895,1.000000e+00
race alone or in combination with one or more other races_total population_black or african american,3112.0,0.098875,0.000000,8.752193e-01
race alone or in combination with one or more other races_total population_american indian and alaska native,3112.0,0.029923,0.000000,9.482386e-01
race alone or in combination with one or more other races_total population_asian,3112.0,0.018213,0.000000,6.115702e-01
race alone or in combination with one or more other races_total population_native hawaiian and other pacific islander,3112.0,0.002067,0.000000,3.343148e-01
race alone or in combination with one or more other races_total population_some other race,3112.0,0.023626,0.000000,5.783582e-01
hispanic or latino and race_total population,3112.0,1.000000,1.000000,1.000000e+00
hispanic or latino and race_total population_hispanic or latino (of any race),3112.0,0.093201,0.000000,9.906877e-01
hispanic or latino and race_total population_hispanic or latino (of any race)_mexican,3112.0,0.069331,0.000000,9.561461e-01
hispanic or latino and race_total population_hispanic or latino (of any race)_puerto rican,3112.0,0.005656,0.000000,3.157797e-01
hispanic or latino and race_total population_hispanic or latino (of any race)_cuban,3112.0,0.001568,0.000000,3.629896e-01
hispanic or latino and race_total population_hispanic or latino (of any race)_other hispanic or latino,3112.0,0.016645,0.000000,7.569581e-01
hispanic or latino and race_total population_not hispanic or latino,3112.0,0.906799,0.009312,1.000000e+00
hispanic or latino and race_total population_not hispanic or latino_white alone,3112.0,0.765065,0.007278,1.000000e+00
hispanic or latino and race_total population_not hispanic or latino_black or african american alone,3112.0,0.088817,0.000000,8.741228e-01
hispanic or latino and race_total population_not hispanic or latino_american indian and alaska native alone,3112.0,0.018016,0.000000,9.096121e-01
hispanic or latino and race_total population_not hispanic or latino_asian alone,3112.0,0.013534,0.000000,4.148463e-01
hispanic or latino and race_total population_not hispanic or latino_native hawaiian and other pacific islander alone,3112.0,0.000780,0.000000,1.116170e-01
hispanic or latino and race_total population_not hispanic or latino_some other race alone,3112.0,0.001097,0.000000,5.483672e-02
hispanic or latino and race_total population_not hispanic or latino_two or more races,3112.0,0.019489,0.000000,2.330136e-01
hispanic or latino and race_total population_not hispanic or latino_two or more races_two races including some other race,3112.0,0.000433,0.000000,1.422370e-02
hispanic or latino and race_total population_not hispanic or latino_two or more races_two races excluding some other race - and three or more races,3112.0,0.019056,0.000000,2.323104e-01
total housing units,3112.0,0.490815,0.253924,2.017974e+00
citizen - voting age population_citizen - 18 and over population,3112.0,0.750649,0.445682,9.074868e-01
citizen - voting age population_citizen - 18 and over population_male,3112.0,0.372103,0.217886,7.185417e-01
citizen - voting age population_citizen - 18 and over population_female,3112.0,0.378546,0.173038,4.718094e-01
sex and age_total population,3112.0,1.000000,1.000000,1.000000e+00
sex and age_total population_male,3112.0,0.500776,0.413863,7.899605e-01
sex and age_total population_female,3112.0,0.499224,0.210039,5.861366e-01
sex and age_total population_sex ratio (males per 100 females),3112.0,100.861054,70.600000,3.761000e+02
sex and age_total population_under 5 years,3112.0,0.058274,0.009281,1.428571e-01
sex and age_total population_5 to 9 years,3112.0,0.061998,0.016174,1.278447e-01
sex and age_total population_10 to 14 years,3112.0,0.064260,0.016885,1.483254e-01
sex and age_total population_15 to 19 years,3112.0,0.064699,0.009174,2.644163e-01
sex and age_total population_20 to 24 years,3112.0,0.062519,0.000000,2.867792e-01
sex and age_total population_25 to 34 years,3112.0,0.117923,0.035022,2.538147e-01
sex and age_total population_35 to 44 years,3112.0,0.115818,0.045429,1.888218e-01
sex and age_total population_45 to 54 years,3112.0,0.129319,0.052870,2.414599e-01
sex and age_total population_55 to 59 years,3112.0,0.072628,0.017089,2.017544e-01
sex and age_total population_60 to 64 years,3112.0,0.068983,0.015126,1.754144e-01
sex and age_total population_65 to 74 years,3112.0,0.105167,0.024984,3.398706e-01
sex and age_total population_75 to 84 years,3112.0,0.055910,0.006536,1.735552e-01
sex and age_total population_85 years and over,3112.0,0.022501,0.000000,8.502538e-02
sex and age_total population_median age (years),3112.0,0.004116,0.000004,2.039474e-01
sex and age_total population_under 18 years,3112.0,0.223623,0.073158,4.049768e-01
sex and age_total population_16 years and over,3112.0,0.802455,0.632349,9.347515e-01
sex and age_total population_18 years and over,3112.0,0.776377,0.595023,9.268424e-01
sex and age_total population_21 years and over,3112.0,0.737593,0.543791,9.107265e-01
sex and age_total population_62 years and over,3112.0,0.223854,0.054333,6.201456e-01
sex and age_total population_65 years and over,3112.0,0.183579,0.037986,5.559633e-01
sex and age_total population_18 years and over_1,3112.0,0.776377,0.595023,9.268424e-01
sex and age_total population_18 years and over_male,3112.0,0.386060,0.287995,7.237111e-01
sex and age_total population_18 years and over_female,3112.0,0.390317,0.174534,4.985799e-01
sex and age_total population_18 years and over_sex ratio (males per 100 females),3112.0,99.632262,70.800000,4.147000e+02
sex and age_total population_65 years and over_1,3112.0,0.183579,0.037986,5.559633e-01
sex and age_total population_65 years and over_male,3112.0,0.084032,0.015325,2.685890e-01
sex and age_total population_65 years and over_female,3112.0,0.099547,0.022662,2.873743e-01

#### d. Check for duplicate columns

There are a lot of columns in this data frame. Let's see if there are any are duplicates. Note that Pandas will not allow them to have the same exact column name, so they will likely be distinct on column name but will be copies otherwise.

In [ ]:
# 101424
# Check for duplicate columns
#-----------
# I used Google to figure this out, and adapted this example for our purposes:  
# source: https://thispointer.com/how-to-find-drop-duplicate-columns-in-a-dataframe-python-pandas/ 
def getDuplicateColumns(df):
    '''
    Get a list of duplicate columns.
    It will iterate over all the columns in dataframe and find the columns whose contents are duplicate.
    :param df: Dataframe object
    :return: List of columns whose contents are duplicates.
    '''
    duplicateColumnNames = set()
    # Iterate over all the columns in dataframe
    for x in range(df.shape[1]):
        # Select column at xth index.
        col = df.iloc[:, x]
        # Iterate over all the columns in DataFrame from (x+1)th index till end
        for y in range(x + 1, df.shape[1]):
            # Select column at yth index.
            otherCol = df.iloc[:, y]
            # Check if two columns at x 7 y index are equal
            if col.equals(otherCol):
                duplicateColumnNames.add(df.columns.values[y])
    return list(duplicateColumnNames)

duplicateColumnNames = list(getDuplicateColumns(______))
print('Duplicate Columns are as follows: ')
duplicateColumnNames

In [ ]:
#
# drop columns from duplicates list
#-----------
# now drop list of duplicate features from our df using the .drop() method
diabetes = diabetes.drop(columns=______)

Finally, there are many states accounted for the in dataset. If we convert this column to a categorical variable, and create dummies, it will create a rather sparse matrix (many 0s in our dataset) becuase there will be 49 dummy variables. One alternative is to classify each state to a larger US region and use that variable instead of state. The following code will do that.

In [ ]:
# Define a dictionary mapping states to regions
state_to_region = {
    'Alabama': 'Southeast',
    'Alaska': 'West',
    'Arizona': 'West',
    'Arkansas': 'South',
    'California': 'West',
    'Colorado': 'West',
    'Connecticut': 'Northeast',
    'Delaware': 'Northeast',
    'District of Columbia': 'Southeast',
    'Florida': 'Southeast',
    'Georgia': 'Southeast',
    'Hawaii': 'West',
    'Idaho': 'West',
    'Illinois': 'Midwest',
    'Indiana': 'Midwest',
    'Iowa': 'Midwest',
    'Kansas': 'Midwest',
    'Kentucky': 'South',
    'Louisiana': 'South',
    'Maine': 'Northeast',
    'Maryland': 'Northeast',
    'Massachusetts': 'Northeast',
    'Michigan': 'Midwest',
    'Minnesota': 'Midwest',
    'Mississippi': 'South',
    'Missouri': 'Midwest',
    'Montana': 'West',
    'Nebraska': 'Midwest',
    'Nevada': 'West',
    'New Hampshire': 'Northeast',
    'New Jersey': 'Northeast',
    'New Mexico': 'West',
    'New York': 'Northeast',
    'North Carolina': 'Southeast',
    'North Dakota': 'Midwest',
    'Ohio': 'Midwest',
    'Oklahoma': 'South',
    'Oregon': 'West',
    'Pennsylvania': 'Northeast',
    'Rhode Island': 'Northeast',
    'South Carolina': 'Southeast',
    'South Dakota': 'Midwest',
    'Tennessee': 'South',
    'Texas': 'South',
    'Utah': 'West',
    'Vermont': 'Northeast',
    'Virginia': 'Southeast',
    'Washington': 'West',
    'West Virginia': 'South',
    'Wisconsin': 'Midwest',
    'Wyoming': 'West'
}

# Add a new 'Region' column based on the mapping
diabetes['Region'] = diabetes['State'].map(state_to_region)

# Print to verify'Region' column has been added
diabetes

## 2. Exploratory Data Analysis

Make at least two figures (feel free to make more) and explain their relevance to the scientific problem. The goal here is to uncover interesting patterns in the data, learn more about the scope of the problem, and communicate these findings to your audience in clear ways.

In [ ]:
#
# EDA #1 and interpretations in this section 
#-----------

In [ ]:
#
# EDA #2 and interpretations in this section 
#-----------

## 3. Prepare to Fit Models

### 3.1 Finalize Data Set

We've already cleaned up the data, but we can make a few more adjustments before partitioning the data and training models. Let's recode 'Region' to be a categorical variable using `pd.get_dummies` and drop 'State'. Also, we'll drop 'County' because 'CountyFIPS' is already a unique identifier for the county.

In [ ]:
#
# Drop and get dummies
#-----------

# create dummy features out of 'Region', which might be related to diabetes rates 
diabetes_clean = pd.get_dummies(______, 
                               columns = [______],  
                               drop_first = True) # drop the first as a reference 

# drop 'County' and 'State' variables
diabetes_clean = diabetes_clean.drop(labels = ['...', '...'],
                               axis = ______) # which axis tells python we want to drop columns rather than index rows?

# look at first 10 rows of new data frame 
diabetes_clean.______

### 3.2 Partition Data, Feature Selection, and Standardization

Now, we will partition our data to prepare it for the training process. Ultimately we want to use a 60% train—20% validation—20% test in this case. More data in the training set lowers bias, but then increases variance in the validation/test sets. Balancing between bias and variance with choice of these set sizes is important as we want to ensure that there is enough data to train on to get good predictions, but also want to make sure our hold-out sets are representative enough.

Work through partitioning the data into the test/train/validation sets in the chunks below. Be sure to that if you are using Ridge or LASSO, you Standardize the data. Where you do this in the workflow matters so be clear about where you are doing this and why.

In [ ]:
#
# Partition data
#-----------

# import library
from sklearn.model_selection import train_test_split

# create y dataframe 
y = ______

# create X dataframe (include everything except "Diabetes_Number", our target, 
# and "race alone or in combination with one or more other races_total population")
X = ______

Investigate whether there are any features that you should remove prior to spliting and model fitting. You may also consider using plots and relationships you found in the EDA stage for this question. Be sure to justify your logic.

In [ ]:
#
# Feature selection
#-----------

In [ ]:
#
# Training/test split
#-----------

# set the random seed
np.random.seed(10)


# split the data so that it returns 4 values: X_train, X_test, y_train, y_test
X_train, X_test, y_train, y_test = train_test_split(...,                 # specify training dataset
                                                    ...,                 # specify test dataset
                                                    train_size=...,      # specify proportional split for training
                                                    test_size=...)       # specify proportional split for test

In [ ]:
#
# Validation split
#-----------

# train_test_split returns 4 values: X_train, X_test, y_train, y_test, so how do we create a 60-20-20 train-validate-test split? 
X_train, X_validate, y_train, y_validate =  ______

In [ ]:
#
# Standardization
#-----------
# Given that we want to only standardize non-dichotomous variables, we need to find a 
# solution that will loop over only the columns we want to standardize. The code below
# identifies all non-dichotomous variables in our dataset and only standardizes those.

# load library and create instance of Standard Scaler 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()


# identify non-dichotomous columns we want to transform
columns = list(X_test.select_dtypes(include=['number']).loc[:, X_test.nunique() > 2])

# use loop to transform training data for only columns we want to transform
for column in columns:
    X_train[column] = scaler.fit_transform(X_train[column].values.reshape(-1, 1)).flatten()

# use loop to transform validation data for only columns we want to transform
for column in columns:
    X_validate[column] = scaler.fit_transform(X_validate[column].values.reshape(-1, 1)).flatten()

# use loop to transform test data for only columns we want to transform
for column in columns:
    X_test[column] = scaler.fit_transform(X_test[column].values.reshape(-1, 1)).flatten()

## 4. Train Models

In this section, train your models. 

**Note that if you use Lasso, you will likely need to specify a very low penalty (e.g., an alpha of 0.001) because of convergence problems.**

### 4.1 Describe models

Detail the basic logic and assumptions underlying each model, its pros/cons, and why it is a plausible choice for this problem.

**MODEL DESCRIPTION(S):** ...

### 4.2 Train models

Train each model in the training set, and be sure to tune hyperparameters if appropriate. Report any relevant summary statistics from the training set, including how well each model fits the training data.

#### Model 1:  (enter name of model here)

In [ ]:
#
# Model 1 training
#-----------

#### Model 2:  (enter name of model here)

In [ ]:
#
# Model 2 training
#-----------

#### Model 3:  (enter name of model here)

In [ ]:
#
# Model 3 training
#-----------

## 5. Validate and Refine Models

### 5.1 Predict on the validation set
Using each of the models you trained, predict outcomes in the validation set. Evaluate how well each model did.

In [ ]:
#
# Predict on validation data
#-----------

### 5.2 Predict on the test set

Now, choose your best performing model of the three, select out unimportant feature(s), retrain the model, and then predict on the test set.

In [ ]:
#
# Predict using your best model
#-----------

### 5.3 Impement a cross-validation approach

Finally, implement a cross-validation approach for your best model and evaluate the results.

In [ ]:
#
# Run cross-validation
#-----------

## 6. Discussion Questions

In this section, insert responses for discussion questions here.

1. What is bias-variance tradeoff? Why is it relevant to machine learning problems like this one?

**YOUR ANSWER HERE**...

2. Define overfitting, and why it matters for machine learning. How can we address it?

**YOUR ANSWER HERE**...

3. Discuss your analysis in 2-3 paragraphs. Discuss your findings and recommendations. Which counties or regions would you prioritize for the pilot program? Would your answers change based on whether you want to take into account certain features such as race, gender, or age composition in the county? How confident would you be deploying this sort of model in a real-world application – why or why not?

**YOUR ANSWER HERE**...